# Generated by Django 2.1.7 on 2019-03-29 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20190328_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summoner',
            name='soloQ_tier',
            field=models.CharField(blank=True, choices=[('CHALLENGER', 'Challenger'), ('GRANDMASTER', 'Grandmaster'), ('MASTER', 'Master'), ('DIAMOND', 'Diamond'), ('PLATINUM', 'Platinum'), ('GOLD', 'Gold'), ('SILVER', 'Silver'), ('BRONZE', 'Bronze'), ('IRON', 'Iron')], max_length=1, null=True),
        ),
    ]
