# Generated by Django 2.1.7 on 2019-03-29 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_auto_20190329_0220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='timestamp',
        ),
    ]
