# Generated by Django 2.1.7 on 2019-04-04 00:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_profile_friends'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roomId', models.CharField(max_length=255)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField()),
                ('members', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ChatRooms', to='dashboard.Profile')),
            ],
        ),
    ]
