# Generated by Django 2.1.7 on 2019-04-16 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_rankedtier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summoner',
            name='flexSR_tier',
            field=models.CharField(blank=True, choices=[('CHALLENGER', 'CHALLENGER'), ('GRANDMASTER', 'GRANDMASTER'), ('MASTER', 'MASTER'), ('DIAMOND', 'DIAMOND'), ('PLATINUM', 'PLATINUM'), ('GOLD', 'GOLD'), ('SILVER', 'SILVER'), ('BRONZE', 'BRONZE'), ('IRON', 'IRON')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='summoner',
            name='flexTT_tier',
            field=models.CharField(blank=True, choices=[('CHALLENGER', 'CHALLENGER'), ('GRANDMASTER', 'GRANDMASTER'), ('MASTER', 'MASTER'), ('DIAMOND', 'DIAMOND'), ('PLATINUM', 'PLATINUM'), ('GOLD', 'GOLD'), ('SILVER', 'SILVER'), ('BRONZE', 'BRONZE'), ('IRON', 'IRON')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='summoner',
            name='soloQ_tier',
            field=models.CharField(blank=True, choices=[('CHALLENGER', 'CHALLENGER'), ('GRANDMASTER', 'GRANDMASTER'), ('MASTER', 'MASTER'), ('DIAMOND', 'DIAMOND'), ('PLATINUM', 'PLATINUM'), ('GOLD', 'GOLD'), ('SILVER', 'SILVER'), ('BRONZE', 'BRONZE'), ('IRON', 'IRON')], max_length=20, null=True),
        ),
    ]
