# Generated by Django 2.1.7 on 2019-04-27 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0024_auto_20190426_0145'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='bots',
            field=models.ManyToManyField(related_name='Matches_bots', to='dashboard.Champion'),
        ),
    ]
