# Generated by Django 2.1.7 on 2019-04-30 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0027_auto_20190430_0017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='bots',
        ),
        migrations.AddField(
            model_name='match',
            name='summoners',
            field=models.ManyToManyField(related_name='Matches', to='dashboard.Summoner'),
        ),
        migrations.AlterField(
            model_name='match',
            name='players',
            field=models.ManyToManyField(related_name='Player_Matches', to='dashboard.Player'),
        ),
    ]
