# Generated by Django 2.1.7 on 2019-05-02 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0029_accesscode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summoner',
            name='summonerLevel',
            field=models.IntegerField(blank=True, default=1),
        ),
    ]
