# Generated by Django 2.1.7 on 2019-05-03 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0030_auto_20190502_0539'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
    ]
