# Generated by Django 2.1.7 on 2019-05-03 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0031_remove_profile_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='last_name',
        ),
    ]
