# Generated by Django 2.1.7 on 2019-05-27 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0033_auto_20190520_0322'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='lane',
            field=models.CharField(choices=[('TOP', 'Top'), ('JUNGLE', 'Jungle'), ('MIDDLE', 'Mid'), ('BOTTOM', 'Bot'), ('NONE', 'None')], default='NONE', max_length=255),
        ),
    ]
