# Generated by Django 2.1.7 on 2019-05-31 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0034_player_lane'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='avatar',
        ),
    ]
