# Generated by Django 2.1.7 on 2019-06-08 00:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0036_auto_20190603_0310'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImprovementLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('good', models.TextField()),
                ('bad', models.TextField()),
                ('lp', models.IntegerField()),
                ('archived', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_logs', to='dashboard.Match')),
                ('opponent', models.ManyToManyField(related_name='opponent_logs', to='dashboard.Champion')),
                ('summoner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='summoner_logs', to='dashboard.Summoner')),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
