# Generated by Django 2.1.7 on 2019-06-18 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0039_auto_20190617_0348'),
    ]

    operations = [
        migrations.AddField(
            model_name='summoner',
            name='thirdParty',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
