# Generated by Django 2.1.7 on 2019-06-25 23:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0042_profile_dark_mode'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThirdPartyVerification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verified', models.BooleanField(default=False)),
                ('archived', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='summoner',
            name='thirdParty',
        ),
        migrations.AddField(
            model_name='thirdpartyverification',
            name='summoner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='summoner_verification', to='dashboard.Summoner'),
        ),
        migrations.AddField(
            model_name='thirdpartyverification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='summoner_verification_user', to='dashboard.Profile'),
        ),
    ]
