# Generated by Django 2.1.7 on 2019-03-18 04:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Summoner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summonerName', models.CharField(max_length=255)),
                ('summonerId', models.CharField(max_length=255, unique=True)),
                ('puuid', models.CharField(max_length=255, unique=True)),
                ('accountId', models.CharField(max_length=255, unique=True)),
                ('server', models.CharField(max_length=255)),
                ('profileIconId', models.IntegerField(blank=True, default=1)),
                ('summonerLevel', models.CharField(blank=True, max_length=255)),
                ('soloQ_leagueId', models.CharField(blank=True, max_length=255)),
                ('soloQ_leagueName', models.CharField(blank=True, max_length=255)),
                ('soloQ_tier', models.CharField(blank=True, max_length=255)),
                ('soloQ_hotStreak', models.BooleanField(default=False)),
                ('soloQ_wins', models.IntegerField(blank=True, default=0, null=True)),
                ('soloQ_losses', models.IntegerField(blank=True, default=0, null=True)),
                ('soloQ_veteran', models.BooleanField(default=False)),
                ('soloQ_rank', models.CharField(blank=True, max_length=255, null=True)),
                ('soloQ_inactive', models.BooleanField(default=False)),
                ('soloQ_freshBlood', models.BooleanField(default=False)),
                ('soloQ_leaguePoints', models.IntegerField(blank=True, default=0, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField()),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
