# Generated by Django 2.2.3 on 2019-07-31 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='currentPlatformId',
        ),
    ]
