# Generated by Django 2.1.7 on 2019-03-18 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platformId', models.IntegerField()),
                ('gameId', models.IntegerField()),
                ('queueId', models.IntegerField()),
                ('seasonId', models.IntegerField()),
                ('mapId', models.IntegerField()),
                ('gameMode', models.CharField(max_length=255)),
                ('gameType', models.CharField(max_length=255)),
                ('gameVersion', models.CharField(max_length=255)),
                ('gameduration', models.IntegerField()),
                ('timestamp', models.IntegerField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
