# Generated by Django 2.1.7 on 2019-03-28 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20190325_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summoner',
            name='date_updated',
            field=models.DateTimeField(null=True),
        ),
    ]
