# Generated by Django 2.1.7 on 2019-03-19 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20190318_2324'),
    ]

    operations = [
        migrations.AddField(
            model_name='match_player',
            name='currentPlatformId',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='match_player',
            name='matchHistoryUri',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='match_player',
            name='platformId',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
