# Generated by Django 2.1.7 on 2019-03-19 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20190319_0432'),
    ]

    operations = [
        migrations.AddField(
            model_name='match_player',
            name='championId',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
