# Generated by Django 2.1.7 on 2019-03-19 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_match_player_championid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match_player',
            name='highestAchievedSeasonTier',
        ),
    ]
