# Generated by Django 2.1.7 on 2019-03-19 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_remove_match_player_highestachievedseasontier'),
    ]

    operations = [
        migrations.RenameField(
            model_name='match',
            old_name='gameduration',
            new_name='gameDuration',
        ),
        migrations.AlterField(
            model_name='match',
            name='platformId',
            field=models.CharField(max_length=255),
        ),
    ]
