# Generated by Django 2.1.7 on 2019-03-19 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_auto_20190319_0516'),
    ]

    operations = [
        migrations.AddField(
            model_name='match_player',
            name='summonerName',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
