# Generated by Django 2.1.7 on 2019-03-19 05:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_match_player_summonername'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match_player',
            name='currentPlatformId',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='match_player',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='dashboard.Match'),
        ),
        migrations.AlterField(
            model_name='match_player',
            name='matchHistoryUri',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='match_player',
            name='platformId',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='match_player',
            name='summonerName',
            field=models.CharField(max_length=255),
        ),
    ]
