# Generated by Django 2.1.7 on 2019-03-20 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_auto_20190319_0522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match_player',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_players', to='dashboard.Match'),
        ),
    ]
