# Generated by Django 2.1.7 on 2019-04-03 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_setting'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='friends',
            field=models.ManyToManyField(related_name='Friends', to='dashboard.Profile'),
        ),
    ]
