# Generated by Django 2.1.7 on 2019-04-10 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_auto_20190404_0055'),
    ]

    operations = [
        migrations.AddField(
            model_name='summoner',
            name='flexSR_freshBlood',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='summoner',
            name='flexSR_hotStreak',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='summoner',
            name='flexSR_inactive',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='summoner',
            name='flexSR_leagueId',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='summoner',
            name='flexSR_leagueName',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='summoner',
            name='flexSR_leaguePoints',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='summoner',
            name='flexSR_losses',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='summoner',
            name='flexSR_rank',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='summoner',
            name='flexSR_tier',
            field=models.CharField(blank=True, choices=[('CHALLENGER', 'Challenger'), ('GRANDMASTER', 'Grandmaster'), ('MASTER', 'Master'), ('DIAMOND', 'Diamond'), ('PLATINUM', 'Platinum'), ('GOLD', 'Gold'), ('SILVER', 'Silver'), ('BRONZE', 'Bronze'), ('IRON', 'Iron')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='summoner',
            name='flexSR_veteran',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='summoner',
            name='flexSR_wins',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='summoner',
            name='flexTT_freshBlood',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='summoner',
            name='flexTT_hotStreak',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='summoner',
            name='flexTT_inactive',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='summoner',
            name='flexTT_leagueId',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='summoner',
            name='flexTT_leagueName',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='summoner',
            name='flexTT_leaguePoints',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='summoner',
            name='flexTT_losses',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='summoner',
            name='flexTT_rank',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='summoner',
            name='flexTT_tier',
            field=models.CharField(blank=True, choices=[('CHALLENGER', 'Challenger'), ('GRANDMASTER', 'Grandmaster'), ('MASTER', 'Master'), ('DIAMOND', 'Diamond'), ('PLATINUM', 'Platinum'), ('GOLD', 'Gold'), ('SILVER', 'Silver'), ('BRONZE', 'Bronze'), ('IRON', 'Iron')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='summoner',
            name='flexTT_veteran',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='summoner',
            name='flexTT_wins',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
    ]
