# Generated by Django 2.1.7 on 2019-04-14 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_auto_20190410_2356'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rune',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('runeId', models.IntegerField(unique=True)),
                ('key', models.CharField(max_length=255)),
                ('icon', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('shortDesc', models.CharField(max_length=255)),
                ('longDesc', models.CharField(max_length=255)),
            ],
        ),
    ]
