# Generated by Django 2.1.7 on 2019-04-14 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_rune'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rune',
            name='longDesc',
            field=models.TextField(),
        ),
    ]
