# Generated by Django 2.1.7 on 2019-04-16 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_auto_20190415_0657'),
    ]

    operations = [
        migrations.CreateModel(
            name='RankedTier',
            fields=[
                ('key', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('order', models.IntegerField()),
            ],
        ),
    ]
