# Generated by Django 2.1.7 on 2019-04-14 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_auto_20190414_0506'),
    ]

    operations = [
        migrations.AddField(
            model_name='rune',
            name='version',
            field=models.CharField(default=None, max_length=255, null=True),
            preserve_default=False,
        ),
    ]
