# Generated by Django 2.1.7 on 2019-04-16 03:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0019_auto_20190416_0321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summoner',
            name='flexSR_tier',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Summoners_FlexSR', to='dashboard.RankedTier'),
        ),
        migrations.AlterField(
            model_name='summoner',
            name='flexTT_tier',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Summoners_FlexTT', to='dashboard.RankedTier'),
        ),
        migrations.AlterField(
            model_name='summoner',
            name='soloQ_tier',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Summoners_SoloQ', to='dashboard.RankedTier'),
        ),
    ]
