# Generated by Django 2.1.7 on 2019-04-14 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0021_auto_20190414_0521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rune',
            name='version',
            field=models.CharField(max_length=255),
        ),
    ]
