# Generated by Django 2.1.7 on 2019-04-14 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0022_auto_20190414_0525'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rune',
            name='id',
        ),
        migrations.AlterField(
            model_name='rune',
            name='runeId',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
