# Generated by Django 2.1.7 on 2019-04-14 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0023_auto_20190414_0531'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='perk0',
        ),
        migrations.AddField(
            model_name='player',
            name='perk0',
            field=models.ManyToManyField(related_name='Runes_1', to='dashboard.Rune'),
        ),
        migrations.RemoveField(
            model_name='player',
            name='perk1',
        ),
        migrations.AddField(
            model_name='player',
            name='perk1',
            field=models.ManyToManyField(related_name='Runes_2', to='dashboard.Rune'),
        ),
        migrations.RemoveField(
            model_name='player',
            name='perk2',
        ),
        migrations.AddField(
            model_name='player',
            name='perk2',
            field=models.ManyToManyField(related_name='Runes_3', to='dashboard.Rune'),
        ),
        migrations.RemoveField(
            model_name='player',
            name='perk3',
        ),
        migrations.AddField(
            model_name='player',
            name='perk3',
            field=models.ManyToManyField(related_name='Runes_4', to='dashboard.Rune'),
        ),
        migrations.RemoveField(
            model_name='player',
            name='perk4',
        ),
        migrations.AddField(
            model_name='player',
            name='perk4',
            field=models.ManyToManyField(related_name='Runes_5', to='dashboard.Rune'),
        ),
        migrations.RemoveField(
            model_name='player',
            name='perk5',
        ),
        migrations.AddField(
            model_name='player',
            name='perk5',
            field=models.ManyToManyField(related_name='Runes_6', to='dashboard.Rune'),
        ),
    ]
