# Generated by Django 2.1.7 on 2019-04-14 05:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0024_auto_20190414_0542'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='perk0',
        ),
        migrations.AddField(
            model_name='player',
            name='perk0',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Player_Runes_1', to='dashboard.Rune'),
        ),
        migrations.RemoveField(
            model_name='player',
            name='perk1',
        ),
        migrations.AddField(
            model_name='player',
            name='perk1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Player_Runes_2', to='dashboard.Rune'),
        ),
        migrations.RemoveField(
            model_name='player',
            name='perk2',
        ),
        migrations.AddField(
            model_name='player',
            name='perk2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Player_Runes_3', to='dashboard.Rune'),
        ),
        migrations.RemoveField(
            model_name='player',
            name='perk3',
        ),
        migrations.AddField(
            model_name='player',
            name='perk3',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Player_Runes_4', to='dashboard.Rune'),
        ),
        migrations.RemoveField(
            model_name='player',
            name='perk4',
        ),
        migrations.AddField(
            model_name='player',
            name='perk4',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Player_Runes_5', to='dashboard.Rune'),
        ),
        migrations.RemoveField(
            model_name='player',
            name='perk5',
        ),
        migrations.AddField(
            model_name='player',
            name='perk5',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Player_Runes_6', to='dashboard.Rune'),
        ),
    ]
