# Generated by Django 2.1.7 on 2019-04-14 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0026_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='item0',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Player_Items_1', to='dashboard.Item'),
        ),
        migrations.AlterField(
            model_name='player',
            name='item1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Player_Items_2', to='dashboard.Item'),
        ),
        migrations.AlterField(
            model_name='player',
            name='item2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Player_Items_3', to='dashboard.Item'),
        ),
        migrations.AlterField(
            model_name='player',
            name='item3',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Player_Items_4', to='dashboard.Item'),
        ),
        migrations.AlterField(
            model_name='player',
            name='item4',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Player_Items_5', to='dashboard.Item'),
        ),
        migrations.AlterField(
            model_name='player',
            name='item5',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Player_Items_6', to='dashboard.Item'),
        ),
        migrations.AlterField(
            model_name='player',
            name='item6',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Player_Items_7', to='dashboard.Item'),
        ),
    ]
