# Generated by Django 2.1.7 on 2019-04-14 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0028_summonerspell'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summonerspell',
            name='cooldown',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='summonerspell',
            name='cost',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='summonerspell',
            name='image_h',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='summonerspell',
            name='image_w',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='summonerspell',
            name='image_x',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='summonerspell',
            name='image_y',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='summonerspell',
            name='maxrank',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='summonerspell',
            name='range',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='summonerspell',
            name='summonerLevel',
            field=models.IntegerField(null=True),
        ),
    ]
