# Generated by Django 2.1.7 on 2019-04-14 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0029_auto_20190414_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summonerspell',
            name='cooldownBurn',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='summonerspell',
            name='costBurn',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='summonerspell',
            name='costType',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='summonerspell',
            name='description',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='summonerspell',
            name='image_full',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='summonerspell',
            name='image_group',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='summonerspell',
            name='image_sprite',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='summonerspell',
            name='maxammo',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='summonerspell',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='summonerspell',
            name='rangeBurn',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='summonerspell',
            name='resource',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='summonerspell',
            name='summonerSpellId',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='summonerspell',
            name='tooltip',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='summonerspell',
            name='version',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
