# Generated by Django 2.1.7 on 2019-04-14 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0030_auto_20190414_1007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summonerspell',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='summonerspell',
            name='tooltip',
            field=models.TextField(null=True),
        ),
    ]
