# Generated by Django 2.1.7 on 2019-04-15 02:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0031_auto_20190414_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='spell1Id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Player_SSpells_1', to='dashboard.SummonerSpell'),
        ),
        migrations.AlterField(
            model_name='player',
            name='spell2Id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Player_SSPells_2', to='dashboard.SummonerSpell'),
        ),
    ]
