# Generated by Django 2.1.7 on 2019-06-03 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0035_remove_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summoner',
            name='server',
            field=models.CharField(choices=[('BR1', 'Brazil'), ('EUN1', 'EU Nordic & East'), ('EUW1', 'EW West'), ('JP1', 'Japan'), ('KR', 'Korea'), ('LA1', 'Latin America North'), ('LA2', 'Latin America South'), ('NA1', 'North America'), ('OC1', 'Oceania'), ('TR1', 'Turkey'), ('RU', 'Russia'), ('PBE1', 'Public Beta Environment')], max_length=255),
        ),
    ]
