# Generated by Django 2.1.7 on 2019-06-08 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0037_auto_20190608_0035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='improvementlog',
            name='bad',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='improvementlog',
            name='good',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='improvementlog',
            name='lp',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='improvementlog',
            name='opponent',
            field=models.ManyToManyField(blank=True, null=True, related_name='opponent_logs', to='dashboard.Champion'),
        ),
    ]
