# Generated by Django 2.1.7 on 2019-06-17 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0038_auto_20190608_0117'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='improvementlog',
            name='opponent',
            field=models.ManyToManyField(related_name='opponent_logs', to='dashboard.Champion'),
        ),
    ]
