# Generated by Django 2.1.7 on 2019-06-20 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0040_summoner_thirdparty'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='premium',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='premium_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
