# Generated by Django 2.1.7 on 2019-06-26 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0043_auto_20190625_2351'),
    ]

    operations = [
        migrations.AddField(
            model_name='thirdpartyverification',
            name='key',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
