# Generated by Django 2.2.2 on 2019-06-28 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0044_thirdpartyverification_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summoner',
            name='server',
            field=models.CharField(choices=[('BR1', 'Brazil'), ('EUN1', 'EU Nordic & East'), ('EUW1', 'EU West'), ('JP1', 'Japan'), ('KR', 'Korea'), ('LA1', 'Latin America North'), ('LA2', 'Latin America South'), ('NA1', 'North America'), ('OC1', 'Oceania'), ('TR1', 'Turkey'), ('RU', 'Russia'), ('PBE1', 'Public Beta Environment')], max_length=255),
        ),
        migrations.AlterField(
            model_name='summoner',
            name='accountId',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='summoner',
            name='summonerId',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AddConstraint(
            model_name='summoner',
            constraint=models.UniqueConstraint(fields=('summonerId', 'server'), name='Unique SummonerId by Server'),
        ),
        migrations.AddConstraint(
            model_name='summoner',
            constraint=models.UniqueConstraint(fields=('accountId', 'server'), name='Unique AccountId by Server'),
        ),
    ]
